import {createRouter,createWebHashHistory} from 'vue-router'
import NProgress from 'nprogress';
import 'nprogress/nprogress.css';

const router = createRouter({
    history:createWebHashHistory(),
    routes:[
        {
            path:'/',
            name:'login',
            meta:{title:'登录'},
            component:()=>import('../views/Login.vue')
        },
        {
            path:'/login',
            redirect:'/'
        },
        {
            path:'/index_S',
            name:'学生端',
            meta:{title:'学生端'},
            component:()=>import('../views/Index_S.vue'),
            children:[
               
                {
                    path:'/sendEmail',
                    name:'发件箱2',
                    meta:{title:'发件箱2'},
                    component:()=>import('../views/student/student-message/sendEmail.vue')
                },
                {
                    path:'/getEmail',
                    name:'收件箱2',
                    meta:{title:'收件箱2'},
                    component:()=>import('../views/student/student-message/getEmail.vue')
                },
                {
                    path:'/S-information',
                    name:'资料信息',
                    meta:{title:'资料信息'},
                    component:()=>import('../views/student/my-profile/S-information.vue')
                },
                {
                    path:'/S-ability-analysis',
                    name:'综合能力分析',
                    meta:{title:'综合能力分析'},
                    component:()=>import('../views/student/my-profile/S-ability-analysis.vue')
                },
                {
                    path:'/S-account-setting',
                    name:'账号设置',
                    meta:{title:'账号设置'},
                    component:()=>import('../views/student/my-profile/S-account-setting.vue')
                },
                {
                    path:'/my-thesis',
                    name:'我的论文',
                    meta:{title:'我的论文'},
                    component:()=>import('../views/student/my-work/my-thesis.vue')
                },
                {
                    path:'/my-patent',
                    name:'我的专利',
                    meta:{title:'我的专利'},
                    component:()=>import('../views/student/my-work/my-patent.vue')
                },
                {
                    path:'/my-award',
                    name:'我的获奖',
                    meta:{title:'我的获奖'},
                    component:()=>import('../views/student/my-work/my-award.vue')
                },
                {
                    path:'/audit-progress',
                    name:'审核进度',
                    meta:{title:'审核进度'},
                    component:()=>import('../views/student/my-work/audit-progress.vue')
                },
                {
                    path:'S-comprtition',
                    name:'赛事指南学生端',
                    meta:{title:'赛事指南学生端'},
                    component:()=>import('../views/student/data-quick/S-competition.vue')
                },
                {
                    path:'/S-sszn',
                    name:'赛事指南3',
                    meta:{title:'赛事指南3'},
                    component:()=>import('../views/student/data-quick/S-sszn.vue')
                },
                {
                    path:'/S-meeting',
                    name:'学术会议学生端',
                    meta:{title:'学术会议学生端'},
                    component:()=>import('../views/student/data-quick/S-meeting.vue')
                
                },
                {
                    path:'/S-square',
                    name:'学术广场',
                    meta:{title:'学术广场'},
                    component:()=>import('../views/student/data-quick/S-square.vue')
                }
            ]
        },
        {
            path:'/Index_T',
            name:'老师端',
            meta:{title:'老师端'},
            component:()=>import('../views/Index_T.vue'),
            children:[
                {
                    path:'/fajianxiang',
                    name:'发件箱',
                    meta:{title:'发件箱'},
                    component:()=>import('../views/teacher/my-message/fajianxiang.vue')
                },
                {
                    path:'/shoujianxiang',
                    name:'收件箱',
                    meta:{title:'收件箱'},
                    component:()=>import('../views/teacher/my-message/shoujianxiang.vue')
                },
                {
                    path:'/shenhe',
                    name:'审核',
                    meta:{title:'审核'},
                    component:()=>import('../views/teacher/student-manage/shenhe.vue')
                },
                {
                    path:'/student-information',
                    name:'学生信息',
                    meta:{title:'学生信息'},
                    component:()=>import('../views/teacher/student-manage/student-information.vue')
                },
                {
                    path:'/saishizhinan',
                    name:'赛事指南',
                    meta:{title:'赛事指南'},
                    component:()=>import('../views/teacher/notice-quick/saishizhinan.vue')
                },
                {
                    path:'/jiaoliuguangchang',
                    name:'交流广场',
                    meta:{title:'交流广场'},
                    component:()=>import('../views/teacher/notice-quick/jiaoliuguangchang.vue')
                },
                
                {
                    path:'/xueshu-meeting',
                    name:'学术会议2',
                    meta:{title:'学术会议2'},
                    component:()=>import('../views/teacher/notice-quick/xueshu-meeting.vue')
                },
                {
                    path:'/teacherinformation',
                    name:'教师个人信息',
                    meta:{title:'教师个人信息'},
                    component:()=>import('../views/teacher/information/index.vue')
                }
            ]
        },
        {
            path:'/Index_U',
            name:'超级管理员端',
            meta:{title:'超级管理员端'},    
            component:()=>import('../views/Index_U.vue'),
            children:[
                {
                    path:'/Administrator',
                    name:'管理员信息管理',
                    meta:{title:'管理员信息管理'},
                    component:()=>import('../views/superUser/usermanage/Administrator.vue')
                },
                {
                    path:'/TeacherData',
                    name:'教师信息管理',
                    meta:{title:'教师信息管理'},
                    component:()=>import('../views/superUser/usermanage/TeacherData.vue')
                },
                {
                    path:'/StudentData',
                    name:'学生信息管理',
                    meta:{title:'学生信息管理'},
                    component:()=>import('../views/superUser/usermanage/StudentData.vue')
                },
                {
                    path:'/document',
                    name:'资料管理',
                    meta:{title:'资料管理'},
                    component:()=>import('../views/superUser/document/document.vue')
                },
                {
                    path:'/audit',
                    name:'待审核结果',
                    meta:{title:'待审核结果'},
                    component:()=>import('../views/superUser/audit/audit.vue')
                },
                {
                    path:'/data-count',
                    name:'数据统计',
                    meta:{title:'数据统计'},
                    component:()=>import('../views/superUser/data-presentation/data-count.vue')
                },
                {
                    path:'/student-data',
                    name:'学生数据分析',
                    meta:{title:'学生数据分析'},
                    component:()=>import('../views/superUser/data-presentation/student-data.vue')
                },
                {
                    path:'/system-notice',
                    name:'系统公告',
                    meta:{title:'系统公告'},
                    component:()=>import('../views/superUser/information-release/system-notice.vue')
                },
                {
                    path:'/meeting',
                    name:'学术会议',
                    meta:{title:'学术会议'},
                    component:()=>import('../views/superUser/information-release/meeting.vue')
                },
                
                {
                    path:'/match',
                    name:'赛事',
                    meta:{title:'赛事指南'},
                    component:()=>import('../views/superUser/information-release/match.vue')
                },
                {
                    path:'/user-xx',
                    name:'个人信息',
                    meta:{title:'个人信息'},
                    component:()=>import('../views/superUser/user-xx.vue')
                }
            ]
        }
    ]
})
router.beforeEach((to,from,next )=>{
    NProgress.start();
    next()
})
router.afterEach((to,from)=>{
    NProgress.done();
    if(to.meta && to.meta.title){
        document.title = to.meta.title
        // console.log(document.title,'document.title');
        
    }
    
})


export default router